In [ ]:
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import r2_score
from sklearn.metrics import accuracy_score
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [15]:
df = pd.read_excel('VacineData.xls',index_col=0)

In [16]:
Training_data=pd.read_excel("VacineData.xls", sheet_name="Sheet2")
Test_data=pd.read_excel("VacineData.xls", sheet_name="Sheet3")

print(Training_data)
print(Test_data)
print(Training_data.columns)
##SourceData_train_dependent=Training_data.columns[[1, 3]].copy() #  New dataframe with only independent variable value for training dataset
SourceData_train_dependent=Training_data[['total']].copy()
SourceData_train_independent= Training_data.drop(Training_data.columns[[0, 1, 3]],axis = 1) # Drop depedent variable from training dataset
print(Training_data.columns)
'''SourceData_train_dependent=Training_data.columns[[1, 3]].copy() #  New dataframe with only independent variable value for training dataset'''
#SourceData_test_dependent=Test_data.columns[[1, 3]].copy()
SourceData_test_dependent=Test_data[['total']].copy()
SourceData_test_independent=Test_data.drop(Test_data.columns[[0, 1, 3]],axis = 1)

##['total','added today']
#print("Line 31")
print(SourceData_train_independent)

         Date  total  ...   prev7DayAv  LastSameDay
0  2020-12-16   1106  ...     0.000000            0
1  2020-12-17   2634  ...   158.000000            0
2  2020-12-18   5535  ...   376.285714            0
3  2020-12-19   6808  ...   790.714286            0
4  2020-12-20   7487  ...   972.571429            0
5  2020-12-21   9843  ...  1069.571429            0
6  2020-12-22  12229  ...  1406.142857            0
7  2020-12-23  14453  ...  1747.000000         1106
8  2020-12-24  14999  ...  1906.714286         1528
9  2020-12-25  14999  ...  1766.428571         2901
10 2020-12-26  15637  ...  1352.000000         1273
11 2020-12-27  16561  ...  1261.285714          679
12 2020-12-28  19816  ...  1296.285714         2356
13 2020-12-29  23183  ...  1424.714286         2386
14 2020-12-30  26920  ...  1564.857143         2224
15 2020-12-31  28203  ...  1781.000000          546
16 2021-01-01  28203  ...  1886.285714            0
17 2021-01-02  28382  ...  1886.285714          638
18 2021-01-0

In [17]:
sc_X = StandardScaler()
X_train=sc_X.fit_transform(SourceData_train_independent.values) #scale the independent variables
y_train=SourceData_train_dependent # scaling is not required for dependent variable
X_test=sc_X.transform(SourceData_test_independent)
y_test=SourceData_test_dependent
'''
X_train = SourceData_train_independent.values
y_train=SourceData_train_dependent # scaling is not required for dependent variable

X_test=SourceData_test_independent
y_test=SourceData_test_dependent'''
print("x")
print(X_train)

print("y")
print(y_train)

x
[[-1.6583124  -1.62711948 -2.48667413 -0.99739063]
 [-1.50755672 -1.52593812 -2.19498894 -0.99739063]
 [-1.35680105 -1.38615048 -1.79200977 -0.99739063]
 [-1.20604538 -1.12075524 -1.02692954 -0.99739063]
 [-1.05528971 -1.00429604 -0.69120147 -0.99739063]
 [-0.90453403 -0.94217837 -0.51212892 -0.99739063]
 [-0.75377836 -0.72664193  0.10921855 -0.99739063]
 [-0.60302269 -0.50836098  0.73847791 -0.09778339]
 [-0.45226702 -0.30490044  1.03332786  0.24546638]
 [-0.30151134 -0.25495015  0.77434517  1.36224823]
 [-0.15075567 -0.25495015  0.00926494  0.03805242]
 [ 0.         -0.19658332 -0.1582035  -0.44510011]
 [ 0.15075567 -0.11205206 -0.09358969  0.91895172]
 [ 0.30151134  0.18572854  0.14350342  0.94335337]
 [ 0.45226702  0.49375535  0.40222238  0.81158449]
 [ 0.60302269  0.83563126  0.80124561 -0.55328073]
 [ 0.75377836  0.9530053   0.99561449 -0.99739063]
 [ 0.90453403  0.9530053   0.99561449 -0.47844902]
 [ 1.05528971  0.96938095  0.8745625  -0.24582003]
 [ 1.20604538  1.01567188  0.

In [18]:
reg = LinearRegression().fit(X_train, y_train)
print("The linear regression score on training data is ", round(reg.score(X_train, y_train),2))


predict=reg.predict(X_test)

#print(y_test)
#print(predict)

print("The R2 score for testing data is ", r2_score(y_test, predict))

futureprections =SourceData_test_independent.copy()
#print(futureprections)
#print(futureprections['days since firstvaccine'].iloc[-1]+1)
#print(predict[-1])
#print((predict[-1] - futureprections["Yesterday's total"].iloc[-7])/7)#futureprections["Yesterday's total"].iloc[-8] replaces the number
#print(predict[-7])
currPredictFrame = pd.DataFrame([[futureprections['days since firstvaccine'].iloc[-1]+1, predict[-1], (predict[-1] - futureprections["Yesterday's total"].iloc[-7])/7, futureprections["Yesterday's total"].iloc[-6] -futureprections["Yesterday's total"].iloc[-7]]], columns=futureprections.columns)

x_predict = sc_X.transform(currPredictFrame)
#print(currPredictFrame)

print("future predictions")

#print(x_predict)
print("Days since first vaccine",futureprections['days since firstvaccine'].iloc[-1]+1,"(1/15)")
newPredict = reg.predict(x_predict)
print(newPredict)
predict = np.append(predict,newPredict)
futureprections = futureprections.append(currPredictFrame)
#print(futureprections)
#print(predict)

while newPredict < 789000:
    currPredictFrame = pd.DataFrame([[futureprections['days since firstvaccine'].iloc[-1]+1, predict[-1], (predict[-1] - futureprections["Yesterday's total"].iloc[-7])/7, futureprections["Yesterday's total"].iloc[-6] -futureprections["Yesterday's total"].iloc[-7]]], columns=futureprections.columns)

    x_predict = sc_X.transform(currPredictFrame)


    newPredict = reg.predict(x_predict)
    print("Days since first vaccine",futureprections['days since firstvaccine'].iloc[-1]+1)
    print("total vaccines",newPredict)
    
    predict = np.append(predict,newPredict)
    futureprections = futureprections.append(currPredictFrame)

print("days after 12/16/20 to vaccinate 50% of philadelphia:",futureprections['days since firstvaccine'].iloc[-1]+1)


The linear regression score on training data is  0.99
The R2 score for testing data is  0.8720586382616973
future predictions
Days since first vaccine 30 (1/15)
[[64771.95634875]]
Days since first vaccine 31
total vaccines [[67642.1618145]]
Days since first vaccine 32
total vaccines [[69481.85000448]]
Days since first vaccine 33
total vaccines [[71880.02292532]]
Days since first vaccine 34
total vaccines [[74806.07916784]]
Days since first vaccine 35
total vaccines [[78396.5489648]]
Days since first vaccine 36
total vaccines [[81350.11966993]]
Days since first vaccine 37
total vaccines [[84819.37725922]]
Days since first vaccine 38
total vaccines [[88172.73143322]]
Days since first vaccine 39
total vaccines [[91051.54042619]]
Days since first vaccine 40
total vaccines [[94115.57431138]]
Days since first vaccine 41
total vaccines [[97435.71621256]]
Days since first vaccine 42
total vaccines [[101147.78459456]]
Days since first vaccine 43
total vaccines [[104672.85559975]]
Days since fir